
runtime! archlinux.vim

filetype plugin indent on
syntax enable
set background=dark
set expandtab
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set number
set backupdir=$HOME/.config/vim
set encoding=utf-8

let &t_ut=''

colorscheme PaperColor


" Статусная строка
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='dark'
let g:airline_enable_fugitive=1
let g:airline_enable_syntastic=1
let g:airline_enable_bufferline=1
"

" Sline
let g:slime_target = "kitty"

" Отступы
let g:indent_guides_enable_on_vim_startup = 1
set ts=4 sw=4 et
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1

" Красивые скобки
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" Автодоп
let g:formatter_yapf_style = 'pep8'
let g:autoformat_verbosemode=1

" Линтер
let g:pymode = 1
let g:pymode_trim_whitespaces = 1
let g:pymode_options = 1
let g:pymode_options_max_line_length = 79
let g:pymode_options_colorcolumn = 1
let g:pymode_python = 'python3'
let g:pymode_indent = 1
let g:pymode_doc = 1
let g:pymode_breakpoint = 1
let g:pymode_lint = 1
let g:pymode_lint_on_fly = 0
let g:pymode_lint_message = 1
let g:pymode_syntax = 1
let g:pymode_syntax_print_as_function = 0
let g:pymode_syntax_all = 1

let g:pymode_syntax_print_as_function = 0
let g:pymode_syntax_highlight_equal_operator = g:pymode_syntax_all
let g:pymode_syntax_space_errors = g:pymode_syntax_all
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_syntax_string_formatting = g:pymode_syntax_all
let g:pymode_syntax_string_format = g:pymode_syntax_all
let g:pymode_syntax_string_templates = g:pymode_syntax_all
let g:pymode_syntax_doctests = g:pymode_syntax_all
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_lint_signs = 1
let g:pymode_lint_cwindow = 0
let g:pymode_lint_todo_symbol = ''
let g:pymode_lint_comment_symbol = ''

"
